apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: karanteenissa-fi-back-depl
  namespace: prod
  labels:
    app: karanteenissa-fi-back-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karanteenissa-fi-back
  template:
    metadata:
      labels:
        app: karanteenissa-fi-back
    spec:
      containers:
      - name: karanteenissa-fi-back
        image: gcr.io/karanteenissa-fi/back:latest
        env:
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: secret-karanteenissa-back
                key: dbaddr
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: secret-karanteenissa-back
                key: jwtsecret
          - name: SYSTEM_EMAIL
            value: karanteenissa2020@gmail.com
          - name: PORT
            value: "80"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args: ["cd /app && npm run start:prod"]