apiVersion: v1
kind: Service
metadata:
  name: karanteenissa-fi-back-svc
  namespace: prod
spec:
  selector:
    app: karanteenissa-fi-back
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80